name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ libgtest-dev
      - name: Build
        run: cmake . && make
      - name: Test
        run: make test
      # - name: CodeCov Upload
      #   uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      # - name: Codacy Upload
      #   uses: codacy/codacy-coverage-reporter-action@v1
      #   with:
      #     project_token: ${{ secrets.CODACY_PROJECT_TOKEN }}
      #     coverage_report: coverage.xml